{% set name = "asv_runner" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/asv_runner-{{ version }}.tar.gz
  sha256: 945dd301a06fa9102f221b1e9ddd048f5ecd863796d4c8cd487f5577fe0db66d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pdm-backend
    - pip
  run:
    - python >=3.7
    - importlib-metadata

test:
  imports:
    - asv_runner
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airspeed-velocity.github.io/asv_runner/
  summary: Core Python benchmark code for ASV
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - HaoZeke
