{% set name = "asv_runner" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 49d88077d8e43f52312178e1627a09de76405291a5d0a20e3dd23feae92cbc95

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }}
    - importlib-metadata

test:
  imports:
    - asv_runner
  commands:
    - pip check
    - python -c "import asv_runner; assert asv_runner.__version__ == '{{ version }}', asv_runner.__version__"
    - python -c "from importlib.metadata import version; assert version('asv_runner') == '{{ version }}'"
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://airspeed-velocity.github.io/asv_runner/
  summary: Core Python benchmark code for ASV
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - HaoZeke
